package com.testlogon.android.feature.call.fsm

/**
 * AND-305 — inputs to the canonical call FSM ([CallFsm.reduce]).
 *
 * Pure (android-free). Events come from three sources: the LOCAL user (StartOutgoing/Accept/Decline/HangUp
 * + the control toggles), the REMOTE peer via signaling/push (IncomingInvite/RemoteAccepted/RemoteDeclined/
 * RemoteEnded/RemoteSignal), and the MEDIA/timer layer (IceConnected/IceDisconnected/IceFailed +
 * InviteTimeout/ReconnectTimeout/HeartbeatTick).
 *
 * [StartOutgoing] carries a pre-generated [callId] so the reducer stays pure (no UUID minting inside
 * reduce). The host mints the id (via CallId.new()) before dispatching.
 *
 * The control toggles (ToggleMute/ToggleCamera/...) are modeled so callers have a single intent channel,
 * but the reducer PASSES THEM THROUGH with NO state change — local media-control state lives in the UI
 * layer, mirroring the existing InCallViewModel (AND-298).
 */
sealed interface CallEvent {

    // ─── Local user intents ────────────────────────────────────────────────────────────────────────

    /** Place an outgoing call. [callId] is pre-generated by the host to keep the reducer pure. */
    data class StartOutgoing(
        val callId: String,
        val peer: PeerRef,
        val isVideo: Boolean,
    ) : CallEvent

    /** Local user accepts a ringing incoming call. */
    data object Accept : CallEvent

    /** Local user declines a ringing incoming call. */
    data object Decline : CallEvent

    /** Local user hangs up (any non-terminal state). */
    data object HangUp : CallEvent

    // ─── Control toggles (passed through; NO state change) ──────────────────────────────────────────

    data object ToggleMute : CallEvent
    data object ToggleCamera : CallEvent
    data object ToggleSpeaker : CallEvent
    data object FlipCamera : CallEvent

    // ─── Remote / signaling-driven ──────────────────────────────────────────────────────────────────

    /** An incoming invite arrived (push/signaling). [callId] is server-assigned. */
    data class IncomingInvite(
        val callId: String,
        val peer: PeerRef,
        val isVideo: Boolean,
    ) : CallEvent

    /** Remote accepted our outgoing invite. */
    data class RemoteAccepted(val callId: String) : CallEvent

    /** Remote declined our outgoing invite. */
    data class RemoteDeclined(val callId: String) : CallEvent

    /** Remote hung up / ended the call. */
    data class RemoteEnded(val callId: String) : CallEvent

    /** A raw signaling payload (SDP/ICE) to forward to the transport seam. NO state change. */
    data class RemoteSignal(val payload: String) : CallEvent

    // ─── Media / ICE ────────────────────────────────────────────────────────────────────────────────

    data object IceConnected : CallEvent
    data object IceDisconnected : CallEvent
    data object IceFailed : CallEvent

    // ─── Timers ─────────────────────────────────────────────────────────────────────────────────────

    /** The invite/ring window elapsed without an answer. */
    data object InviteTimeout : CallEvent

    /** The reconnect window elapsed without recovery. */
    data object ReconnectTimeout : CallEvent

    /** A billing/keepalive heartbeat tick fired (passed through; NO state change). */
    data object HeartbeatTick : CallEvent
}
