// Pure, framework-free helpers for multi-protocol trading/custody credentials.
// Used by the API-key management surface to provision REST/WS/FIX/Binary access.

export type Protocol = "rest" | "ws" | "fix" | "binary";

export const ALL_PROTOCOLS: Protocol[] = ["rest", "ws", "fix", "binary"];

const PROTOCOL_LABELS: Record<Protocol, string> = {
  rest: "REST",
  ws: "WebSocket",
  fix: "FIX",
  binary: "Binary",
};

/** Human-readable label for a protocol. */
export function protocolLabel(protocol: Protocol): string {
  return PROTOCOL_LABELS[protocol] ?? String(protocol).toUpperCase();
}

// Scope groups mirrored from the create dialog. Kept here so the validator is pure.
export const TRADING_SCOPES = [
  "trading:read",
  "trading:orders",
  "trading:cancel",
  "trading:positions",
  "trading:funding",
];

export const CUSTODY_SCOPES = [
  "custody:read",
  "custody:deposit",
  "custody:withdraw",
  "custody:transfer",
];

export const MARKETDATA_SCOPES = ["marketdata:read", "marketdata:stream"];

/**
 * Scopes that a given protocol is expected to carry at minimum.
 * REST is generic (any scope). WS needs a stream/read scope. FIX and Binary
 * are order-entry / custody transports and require at least one
 * trading-or-custody scope to be meaningful.
 */
export function protocolRequiresScopes(protocol: Protocol): string[] {
  switch (protocol) {
    case "fix":
    case "binary":
      return [...TRADING_SCOPES, ...CUSTODY_SCOPES];
    case "ws":
      return [...TRADING_SCOPES, ...CUSTODY_SCOPES, ...MARKETDATA_SCOPES];
    case "rest":
    default:
      return [];
  }
}

function isTradingOrCustodyScope(scope: string): boolean {
  return TRADING_SCOPES.includes(scope) || CUSTODY_SCOPES.includes(scope);
}

export interface ProtocolValidationError {
  protocol: Protocol;
  message: string;
}

/**
 * Validate a selected set of protocols against the selected scopes.
 * FIX and Binary require at least one trading-or-custody scope.
 * WS requires at least one of trading/custody/marketdata.
 * REST imposes no requirement. Returns a list of errors (empty === valid).
 */
export function validateProtocolScopes(
  protocols: Protocol[],
  scopes: string[],
): ProtocolValidationError[] {
  const errors: ProtocolValidationError[] = [];
  const scopeSet = new Set(scopes);
  for (const protocol of protocols) {
    if (protocol === "fix" || protocol === "binary") {
      const ok = scopes.some(isTradingOrCustodyScope);
      if (!ok) {
        errors.push({
          protocol,
          message: `${protocolLabel(protocol)} requires at least one Trading or Custody scope.`,
        });
      }
    } else if (protocol === "ws") {
      const allowed = protocolRequiresScopes("ws");
      const ok = allowed.some((s) => scopeSet.has(s));
      if (!ok) {
        errors.push({
          protocol,
          message: `${protocolLabel(protocol)} requires at least one Trading, Custody, or Market Data scope.`,
        });
      }
    }
  }
  return errors;
}

export interface FixSessionParams {
  senderCompId: string;
  targetCompId: string;
  host: string;
  port: number | string;
  username?: string;
  password?: string;
  msgTypes?: string[];
  beginString?: string;
  heartBtInt?: number;
}

/**
 * Build a downloadable QuickFIX-style initiator session config (.cfg text)
 * from the supplied session parameters. Pure string builder.
 */
export function buildFixSessionConfig(params: FixSessionParams): string {
  const {
    senderCompId,
    targetCompId,
    host,
    port,
    username,
    password,
    msgTypes,
    beginString = "FIX.4.4",
    heartBtInt = 30,
  } = params;

  const lines: string[] = [];
  lines.push("# QuickFIX session configuration");
  lines.push("# Generated by the credential manager. Store securely.");
  lines.push("");
  lines.push("[DEFAULT]");
  lines.push("ConnectionType=initiator");
  lines.push("ReconnectInterval=5");
  lines.push(`HeartBtInt=${heartBtInt}`);
  lines.push("FileStorePath=store");
  lines.push("FileLogPath=log");
  lines.push("StartTime=00:00:00");
  lines.push("EndTime=00:00:00");
  lines.push("UseDataDictionary=Y");
  lines.push("ResetOnLogon=Y");
  lines.push("");
  lines.push("[SESSION]");
  lines.push(`BeginString=${beginString}`);
  lines.push(`SenderCompID=${senderCompId}`);
  lines.push(`TargetCompID=${targetCompId}`);
  lines.push(`SocketConnectHost=${host}`);
  lines.push(`SocketConnectPort=${port}`);
  if (username) lines.push(`Username=${username}`);
  if (password) lines.push(`Password=${password}`);
  if (msgTypes && msgTypes.length > 0) {
    lines.push(`# Permitted MsgTypes: ${msgTypes.join(", ")}`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Filename for a downloaded FIX session config. */
export function fixConfigFilename(senderCompId: string): string {
  const safe = (senderCompId || "session").replace(/[^A-Za-z0-9_.-]+/g, "_");
  return `fix-${safe}.cfg`;
}

/** Format a WS subscribe payload as a JSON string for display/copy. */
export function wsSubscribePayload(sub: string): string {
  return JSON.stringify({ sub });
}

/** The subscribe channels a WS credential exposes, given optional server-provided list. */
export function wsSubscribeChannels(subs?: string[]): string[] {
  if (subs && subs.length > 0) return subs;
  return ["events", "custody"];
}
